pipeline{
 agent any
 environment {
   ANYPOINT = credentials('deploy-anypoint-user')
  }
 stages {
 	stage ('Build'){
 		steps {
 			withMaven(maven:'maven'){
 				sh 'mvn -f testmunitsample/pom.xml clean install'
 			}
 		}
 	}
 	
 }

}